export const BIOMARKERS = [
  {
    id: 'insulin',
    name: 'Fasting Insulin',
    unit: 'µIU/mL',
    conventionalMin: 2,
    conventionalMax: 25,
    functionalMin: 2,
    functionalMax: 5,
    sliderMin: 0,
    sliderMax: 30,
    sliderStep: 0.5,
    subtitle: 'Direct driver of metabolic health, silent cellular inflammation, sleep quality, and sugar crashes.',
    conventionalText: 'Conventional pathology allows levels up to 25 µIU/mL before flagging disease, leaving insulin-resistant blockages untreated for years.',
    functionalText: 'We target < 5 µIU/mL to prevent subclinical fat storage, preserve pancreatic cell longevity, and sustain reliable fat-burning speed.'
  },
  {
    id: 'tsh',
    name: 'Thyroid Stimulating Hormone (TSH)',
    unit: 'µIU/mL',
    conventionalMin: 0.45,
    conventionalMax: 4.5,
    functionalMin: 1.0,
    functionalMax: 2.0,
    sliderMin: 0.1,
    sliderMax: 10.0,
    sliderStep: 0.1,
    subtitle: 'The master regulator of baseline metabolic output, cognitive energy, and hormone feedback loops.',
    conventionalText: 'A massive conventional window of 0.45 - 4.5 µIU/mL keeps millions suffering from unexplained fatigue and cold hands marked as "normal."',
    functionalText: 'Clinically targeting a narrow 1.0 - 2.0 µIU/mL secures maximum baseline oxygen delivery and constant daily biological recovery.'
  },
  {
    id: 'ferritin',
    name: 'Ferritin (Iron Reserve)',
    unit: 'ng/mL',
    conventionalMin: 15,
    conventionalMax: 150,
    sliderMin: 5,
    sliderMax: 250,
    sliderStep: 1,
    subtitle: 'The cellular iron battery that direct-fuels oxygen transport and mitochondrial energy (ATP) generation.',
    conventionalText: 'A conventional threshold as low as 15 ng/mL permits intense physical fatigue before classical pathology diagnoses clinical anemia.',
    functionalMin: 50,
    functionalMax: 100,
    functionalText: 'Optimising to 50 - 100 ng/mL provides structural raw material for thyroid enzymatic conversion and deep cellular endurance.'
  },
  {
    id: 'vitD',
    name: 'Active Vitamin D3',
    unit: 'ng/mL',
    conventionalMin: 20,
    conventionalMax: 100,
    sliderMin: 10,
    sliderMax: 150,
    sliderStep: 1,
    subtitle: 'A structural secosteroid hormone that governs cellular genetic transcription and multi-organ immune response.',
    conventionalText: '20 ng/mL seeks purely to prevent basic bone softening, completely ignoring active modern immunity and endocrine balance.',
    functionalMin: 60,
    functionalMax: 90,
    functionalText: 'Maintaining a 60 - 90 ng/mL zone serves to unlock deep gene transcription, guard mucosal surfaces, and support hormonal pathways.'
  }
];
